### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by poettering** [majek/csiphash#3]
Heya, 

the key array parameter is currently defined to "const char key[16]". Given the basic type of the array the compiler is free to align this array to any boundary it likes, including uneven ones. However, in the first line of the function you then cast the array to "const uint64_t*", which implies 8 byte alignment, and you then go and access it like that. That will work on x86 (albeit slowly), but break badly on other archs, where unaligned accesses result in SIGBUS.

if you access the array as two 64bit entities you have to tell the compiler that the array should be aligned to an 8byte boundary. You could do that with some C11 or compiler specific decorators, however I'd simply recommend to change the parameter array to be of the type "const uint64[2]". Another alternative would be to go via unions, but that makes the prototype more complex.

(Another nitpick: I'd prefer if the call would be C89-clean, i.e. not declare variables in the middle of everything.)

Thanks,

Lennart

**Comment by poettering** [comment]
Hmm, so thinking about it, for what you are trying to do, the redefiniton to an uint64_t[2] array parameter won't work.

You still have to the option to memcpy() before applying the le conversion.

**Comment by poettering** [comment]
Oh, hmm, the same problem you actually have with the src array, too... Nasty...

**Comment by majek** [comment]
Feel free to submit a pull request if you know how to make the code cleaner and faster.
