### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by StefanKarpinski** [majek/csiphash#4]
This repo needs a LICENSE file indicating under what terms people can use and/or redistribute it. The [reference implementation](https://131002.net/siphash/siphash24.c), which you [indicate](https://idea.popcount.org/2013-01-24-siphash/) you based this on is public domain, meaning you can pick any license you want, including making it public domain. This is not the default, however, (at least not in the US). I would recommend [MIT License](http://opensource.org/licenses/MIT) as simple, well-known, very close to public domain, while still providing some measure of protection from being sued.

Also, hi, Marek :-)

**Comment by majek** [comment]
Hi Stefan :)

This repo is pretty much a single file, intentionally. There is a license at the top of the file. do you think it's enough?

**Comment by StefanKarpinski** [comment]
Ah, right. I scrolled right past that when looking at the code. I think it would be more obvious in a separate LICENSE file, but it might also be enough to just mention it in the README.
